# Use offocial python slim image
FROM python:3.11-slim

# Set working directory inside the container
WORKDIR /app

# Copy requirements first for better layer caching
# If requirements don't change, Docker won't reinstall packages on every build
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the backend code
COPY . .

# Default command - verridden per service in docker-compose.yml
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "8000"]

